name: Call a reusable workflow Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  #call-workflow:
    #uses: codeclubbentleigh/hello-action/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: codeclubbentleigh/hello-action/.github/workflows/workflow-B.yml@dev
    with:
      name: development
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
